import { Josefin_Sans, Open_Sans, Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";

const josefinSans = Josefin_Sans({
  variable: "--font-josefin-sans",
  subsets: ["latin"]
})

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"]
})

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400"]
})

export const metadata = {
  title: "GA.ME",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pl">
      <body className={`${josefinSans.variable} antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
